sudo service themis-99bill restart
sudo service themis-chinaums restart
sudo service themis-fraudmetrix restart
sudo service themis-creditchina restart
sudo service themis-sms	restart
sudo service themis-daemon restart
sudo service themis-provider restart
sudo servcie themis-http restart
sudo service themis-manage restart
sudo service themis-test restart
